project:
  type: website
  output-dir: docs

website:
  title: "SIGERIP"
  navbar:
    logo: img.jpg
    left:
      - href: index.qmd
        text: Início
      - href: dados_mortalidade.qmd
        text: Dados de Mortalidade
      - href: previsao_mortalidade.qmd
        text: Previsão de Mortalidade
      - href: expectativa_de_vida.qmd
        text: Expectativa de Vida
      - href: prev_exp_vida.qmd
        text: Previsão de Expectativa de Vida
    right:  
      - icon: github
        href: https://github.com/Sigerip
      - icon: instagram
        href: https://www.instagram.com/sigerip.ufpb/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



